name: bazzite-custom-image
description: Custom Bazzite GNOME with OpenConnect COPR for Adidas VPN
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: stable

modules:
  # OpenConnect COPR for Adidas VPN
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/dwmw2/openconnect/repo/fedora-43/dwmw2-openconnect-fedora-43.repo
    install:
      - openconnect
      - NetworkManager-openconnect
      - NetworkManager-openconnect-gnome

  # Browsers as native RPMs (split into separate modules to avoid RPM lock conflicts)

  # Firefox Developer Edition
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/the4runner/firefox-dev/repo/fedora-43/the4runner-firefox-dev-fedora-43.repo
    install:
      - firefox-dev

  # Google Chrome
  - type: rpm-ostree
    repos:
      - google-chrome.repo
    install:
      - google-chrome-stable

  # Vivaldi
  - type: rpm-ostree
    repos:
      - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
    install:
      - vivaldi-stable

  # Microsoft Edge
  - type: rpm-ostree
    repos:
      - microsoft-edge.repo
    install:
      - microsoft-edge-stable

  # Mailspring email client (installed via direct RPM download)
  - type: rpm-ostree
    install:
      - https://github.com/Foundry376/Mailspring/releases/download/1.16.0/mailspring-1.16.0-0.1.x86_64.rpm

  # Google Antigravity IDE (AI-powered development platform)
  - type: rpm-ostree
    repos:
      - antigravity.repo
    install:
      - antigravity

  # Teams for Linux (native RPM)
  - type: rpm-ostree
    repos:
      - https://repo.teamsforlinux.de/rpm/teams-for-linux.repo
    keys:
      - https://repo.teamsforlinux.de/teams-for-linux.asc
    install:
      - teams-for-linux

  # ============================================================================

  # Warp Terminal (stable and preview channels)
  - type: rpm-ostree
    repos:
      - warp-terminal.repo
    install:
      - warp-terminal
      - warp-terminal-preview

  # VS Code
  - type: rpm-ostree
    repos:
      - vscode.repo
    install:
      - code

  # Core system tools and multimedia
  - type: rpm-ostree
    install:
      - neovim              # Modern text editor
      - vlc                 # Media player
      - ffmpeg              # Multimedia framework
      - speedtest-cli       # Internet speed test
      - nodejs              # Required for Gemini CLI

  # Flatpak applications
  - type: default-flatpaks@v1
    notify: true
    system:
      install:
        # Workspace and productivity
        - org.ferdium.Ferdium                             # Workspace organizer
        - io.github.zaedus.spider                         # Install & integrate web apps
        
        # Screenshot and image tools
        - be.alexandervanhee.gradia                       # Screenshot annotation tool
        
        # API debugging and development
        - com.reqable.Reqable                             # HTTP proxy & REST client
        
        # Note-taking and knowledge management
        - com.logseq.Logseq                               # Local-first knowledge base
        - org.standardnotes.standardnotes                 # Encrypted notes
        
        # Remote desktop and networking
        - de.capypara.FieldMonitor                        # Remote desktop client (RDP/VNC/SPICE)
        - io.github.zingytomato.netpeek                   # Network scanner
        
        # Container management
        - io.podman_desktop.PodmanDesktop                 # Podman GUI

        # Hardware management
        - io.github.pwr_solaar.solaar                     # Logitech device manager

  # GNOME Extensions
  - type: gnome-extensions
    install:
      - Dash to Dock                                      # Customizable dock
      - Dash to Panel                                     # Taskbar-style panel
      - Clipboard Indicator                               # Clipboard history manager
      - Desktop Icons NG (GNOME 40+)                     # Desktop icons support
      - Extension List                                    # Manage extensions from panel
      - Just Perfection                                   # Customize GNOME Shell
      - Quick Close in Overview                           # Close windows with middle-click
      - Tiling Shell                                      # Advanced window tiling
      - Vitals                                            # System monitor in top bar
      - Weather O'Clock                                   # Weather in clock area
      - Weather or Not                                    # Weather indicator in panel

  # AI CLI Tools Installation
  - type: script
    snippets:
      # Claude CLI (native binary installation)
      - |
        echo "Installing Claude CLI (native binary)..."
        curl -fsSL https://claude.ai/install.sh | bash -s -- --prefix=/usr/local
        echo "Claude CLI installed successfully"

      # Gemini CLI (requires Node.js - installed via npm)
      - |
        echo "Installing Gemini CLI..."
        npm install -g @google/gemini-cli
        echo "Gemini CLI installed successfully"

      # OpenAI Codex CLI (download Rust binary from GitHub)
      - |
        echo "Installing OpenAI Codex CLI..."
        ARCH=$(uname -m)
        if [ "$ARCH" = "x86_64" ]; then
          CODEX_URL="https://github.com/openai/codex/releases/latest/download/codex-x86_64-unknown-linux-gnu.tar.gz"
        elif [ "$ARCH" = "aarch64" ]; then
          CODEX_URL="https://github.com/openai/codex/releases/latest/download/codex-aarch64-unknown-linux-gnu.tar.gz"
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi
        curl -L "$CODEX_URL" -o /tmp/codex.tar.gz
        tar -xzf /tmp/codex.tar.gz -C /tmp
        install -m 0755 /tmp/codex /usr/local/bin/codex
        rm -rf /tmp/codex.tar.gz /tmp/codex
        echo "OpenAI Codex CLI installed successfully"

  # DeepCool Digital Linux - RGB and display control for DeepCool hardware
  - type: script
    snippets:
      - |
        # Download and install DeepCool Digital Linux binary
        echo "Downloading DeepCool Digital Linux v0.10.1-alpha..."
        curl -L "https://github.com/Nortank12/deepcool-digital-linux/releases/download/v0.10.1-alpha/deepcool-digital-linux" -o /tmp/deepcool-digital-linux
        chmod +x /tmp/deepcool-digital-linux
        install -m 0755 /tmp/deepcool-digital-linux /usr/sbin/deepcool-digital-linux
        rm /tmp/deepcool-digital-linux
        echo "DeepCool Digital Linux installed successfully"

  # Install system configuration files (systemd services, udev rules, etc.)
  - type: files
    files:
      - source: system
        destination: /

  # Enable automatic updates
  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer                     # Auto-update system daily
        - deepcool-digital-linux.service                  # DeepCool hardware control
    user:
      enabled:
        - flatpak-automatic.timer                         # Auto-update Flatpaks

  # Configure rpm-ostree auto-update policy
  - type: files
    files:
      - system: system
        # Copies rpm-ostreed.conf with AutomaticUpdatePolicy=stage
