name: bazzite-custom-image
description: Custom Bazzite GNOME with OpenConnect COPR for Adidas VPN
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: stable

modules:
  # OpenConnect COPR for Adidas VPN
  - type: script
    scripts:
      - openconnect-copr.sh
  
  # Install NetworkManager packages
  - type: rpm-ostree
    install:
      - NetworkManager-openconnect
      - NetworkManager-openconnect-gnome
            
  # Browsers as native RPMs (split into separate modules to avoid RPM lock conflicts)

  # Firefox Developer Edition
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/the4runner/firefox-dev/repo/fedora-43/the4runner-firefox-dev-fedora-43.repo
    install:
      - firefox-dev

  # Google Chrome
  - type: rpm-ostree
    repos:
      - google-chrome.repo
    install:
      - google-chrome-stable

  # Vivaldi
  - type: rpm-ostree
    repos:
      - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
    install:
      - vivaldi-stable

  # Microsoft Edge
  - type: rpm-ostree
    repos:
      - microsoft-edge.repo
    install:
      - microsoft-edge-stable

  # Mailspring email client (installed via direct RPM download)
  - type: rpm-ostree
    install:
      - https://github.com/Foundry376/Mailspring/releases/download/1.16.0/mailspring-1.16.0-0.1.x86_64.rpm

  # Google Antigravity IDE (AI-powered development platform)
  - type: rpm-ostree
    repos:
      - antigravity.repo
    install:
      - antigravity

  # Teams for Linux (native RPM)
  - type: rpm-ostree
    repos:
      - https://repo.teamsforlinux.de/rpm/teams-for-linux.repo
    keys:
      - https://repo.teamsforlinux.de/teams-for-linux.asc
    install:
      - teams-for-linux

  # ============================================================================

  # Warp Terminal (stable and preview channels)
  - type: rpm-ostree
    repos:
      - warp-terminal.repo
    install:
      - warp-terminal
      - warp-terminal-preview

  # VS Code
  - type: rpm-ostree
    repos:
      - vscode.repo
    install:
      - code

  # Core system tools and multimedia
  - type: rpm-ostree
    install:
      - neovim              # Modern text editor
      - vlc                 # Media player
      - ffmpeg              # Multimedia framework
      - speedtest-cli       # Internet speed test

  # Flatpak applications
  - type: default-flatpaks@v1
    notify: true
    system:
      install:
        # Workspace and productivity
        - org.ferdium.Ferdium                             # Workspace organizer
        - io.github.zaedus.spider                         # Install & integrate web apps
        
        # Screenshot and image tools
        - be.alexandervanhee.gradia                       # Screenshot annotation tool
        
        # API debugging and development
        - com.reqable.Reqable                             # HTTP proxy & REST client
        
        # Note-taking and knowledge management
        - com.logseq.Logseq                               # Local-first knowledge base
        - org.standardnotes.standardnotes                 # Encrypted notes
        
        # Remote desktop and networking
        - de.capypara.FieldMonitor                        # Remote desktop client (RDP/VNC/SPICE)
        - io.github.zingytomato.netpeek                   # Network scanner
        
        # Container management
        - io.podman_desktop.PodmanDesktop                 # Podman GUI

        # Hardware management
        - io.github.pwr_solaar.solaar                     # Logitech device manager

  # GNOME Extensions (using PK IDs to avoid ambiguity)
  - type: gnome-extensions
    install:
      - 307   # Dash to Dock - Customizable dock
      - 1160  # Dash to Panel - Taskbar-style panel
      - 779   # Clipboard Indicator - Clipboard history manager
      - 2087  # Desktop Icons NG (GNOME 40+) - Desktop icons support
      - 3088  # Extension List - Manage extensions from panel
      - 3843  # Just Perfection - Customize GNOME Shell
      - 352   # Quick Close in Overview - Close windows with middle-click
      - 7065  # Tiling Shell - Advanced window tiling
      - 1460  # Vitals - System monitor in top bar
      - 5470  # Weather O'Clock - Weather in clock area
      - 5660  # Weather or Not - Weather indicator in panel

  # DeepCool Digital Linux - RGB and display control for DeepCool hardware
  - type: script
    snippets:
      - |
        # Download and install DeepCool Digital Linux binary
        echo "Downloading DeepCool Digital Linux v0.10.1-alpha..."
        curl -L "https://github.com/Nortank12/deepcool-digital-linux/releases/download/v0.10.1-alpha/deepcool-digital-linux" -o /tmp/deepcool-digital-linux
        chmod +x /tmp/deepcool-digital-linux
        install -m 0755 /tmp/deepcool-digital-linux /usr/sbin/deepcool-digital-linux
        rm /tmp/deepcool-digital-linux
        echo "DeepCool Digital Linux installed successfully"

  # Install system configuration files (systemd services, udev rules, etc.)
  - type: files
    files:
      - source: system
        destination: /

  # Enable automatic updates
  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer                     # Auto-update system daily
        - deepcool-digital-linux.service                  # DeepCool hardware control
