name: bazzite-custom-image
description: Custom Bazzite GNOME with OpenConnect COPR for Adidas VPN
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: stable

modules:
  # OpenConnect COPR for Adidas VPN
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/dwmw2/openconnect/repo/fedora-43/dwmw2-openconnect-fedora-43.repo
    install:
      - openconnect
      - NetworkManager-openconnect
      - NetworkManager-openconnect-gnome

  # Browsers as native RPMs
  # Note: Firefox Dev COPR doesn't have F43 builds yet - install manually later
  - type: rpm-ostree
    repos:
      - https://dl.google.com/linux/chrome/rpm/stable/x86_64
      - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
      - https://packages.microsoft.com/yumrepos/edge
    install:
      - google-chrome-stable
      - vivaldi-stable
      - microsoft-edge-stable

  # Warp Terminal (stable and preview channels)
  - type: rpm-ostree
    repos:
      - https://releases.warp.dev/linux/rpm/stable
      - https://releases.warp.dev/linux/rpm/preview
    install:
      - warp-terminal
      - warp-terminal-preview

  # VS Code
  - type: rpm-ostree
    repos:
      - https://packages.microsoft.com/yumrepos/vscode
    install:
      - code

  # Core system tools and multimedia
  - type: rpm-ostree
    install:
      - neovim              # Modern text editor
      - vlc                 # Media player
      - ffmpeg              # Multimedia framework
      - speedtest-cli       # Internet speed test

  # Google Antigravity IDE (AI-powered development platform)
  - type: rpm-ostree
    repos:
      - https://us-central1-yum.pkg.dev/projects/antigravity-auto-updater-dev/antigravity-rpm
    install:
      - antigravity

  # Teams for Linux (native RPM)
  - type: rpm-ostree
    repos:
      - https://repo.teamsforlinux.de/rpm/teams-for-linux.repo
    keys:
      - https://repo.teamsforlinux.de/teams-for-linux.asc
    install:
      - teams-for-linux

  # Flatpak applications
  - type: default-flatpaks
    notify: true
    system:
      install:
        # Workspace and productivity
        - org.ferdium.Ferdium                             # Workspace organizer
        - io.github.zaedus.spider                         # Install & integrate web apps
        
        # Screenshot and image tools
        - be.alexandervanhee.gradia                       # Screenshot annotation tool
        
        # API debugging and development
        - com.reqable.Reqable                             # HTTP proxy & REST client
        
        # Note-taking and knowledge management
        - com.logseq.Logseq                               # Local-first knowledge base
        - org.standardnotes.standardnotes                 # Encrypted notes
        
        # Remote desktop and networking
        - de.capypara.FieldMonitor                        # Remote desktop client (RDP/VNC/SPICE)
        - io.github.zingytomato.netpeek                   # Network scanner
        
        # Container management
        - io.podman_desktop.PodmanDesktop                 # Podman GUI

  # GNOME Extensions
  - type: gnome-extensions
    install:
      - Dash to Dock                                      # Customizable dock
      - Dash to Panel                                     # Taskbar-style panel
      - Clipboard Indicator                               # Clipboard history manager
      - Desktop Icons NG (GNOME 40+)                     # Desktop icons support
      - Extension List                                    # Manage extensions from panel
      - Just Perfection                                   # Customize GNOME Shell
      - Quick Close in Overview                           # Close windows with middle-click
      - Tiling Shell                                      # Advanced window tiling
      - Vitals                                            # System monitor in top bar
      - Weather O'Clock                                   # Weather in clock area
      - Weather or Not                                    # Weather indicator in panel

  # Enable automatic updates
  - type: systemd
    system:
      enabled:
        - rpm-ostreed-automatic.timer                     # Auto-update system daily
    user:
      enabled:
        - flatpak-automatic.timer                         # Auto-update Flatpaks

  # Configure rpm-ostree auto-update policy
  - type: files
    files:
      - system: system
        # Copies rpm-ostreed.conf with AutomaticUpdatePolicy=stage
